name: Tox

on:
  push:
    branches-ignore:
      - master
    tags-ignore:
      - "*"

jobs:
  python:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.10', '3.11']

    steps:
    - name: Check out repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install Tox
      run: |
        pip install tox

    - name: Run Tox
      run: tox -e py
